import streamlit as st
import pandas as pd
import subprocess
import os

st.set_page_config(page_title="Fairness Pipeline", layout="wide", page_icon="⚖️")

st.title("⚖️ Fair ML Platform")
st.markdown("Automated Bias Detection, Mitigation, and Structural Network Analysis for the GDG Solution Challenge.")

# --- SIDEBAR configuration ---
st.sidebar.header("Data Configuration")

uploaded_file = st.sidebar.file_uploader("Upload your own CSV", type=["csv"])

target_col = st.sidebar.text_input("Target Column", value="Loan_Status")
sensitive_col = st.sidebar.text_input("Sensitive Column (e.g. Gender)", value="Gender")

st.sidebar.markdown("---")
st.sidebar.info("By default, if no CSV is uploaded, it uses `data.csv`.")

if st.sidebar.button("🚀 Run Fairness Analysis", type="primary"):
    
    with st.spinner("Analyzing Data and Running Fairness Pipelines..."):
        # Handle file
        csv_path = "data.csv"
        if uploaded_file is not None:
            # save locally to be processed by pipeline
            temp_csv = "uploaded_data.csv"
            with open(temp_csv, "wb") as f:
                f.write(uploaded_file.getbuffer())
            csv_path = temp_csv
            
        # Optional: remove old images so we don't show stale ones if it fails
        for img in ["metrics_tradeoff.png", "structural_bias.png"]:
            if os.path.exists(img):
                os.remove(img)

        # Run pipeline
        try:
            # Use the correct python binary from the assumed environment (if accessible, else fallback)
            # sys.executable is usually safer, but since the user has a venv, we can assume standard run
            python_cmd = "python"
            if os.path.exists("venv/bin/python"):
                python_cmd = "venv/bin/python"

            cmd = [python_cmd, "ml_pipeline.py", "--csv", csv_path, "--target_col", target_col, "--sensitive_col", sensitive_col]
            
            # Execute
            result = subprocess.run(cmd, capture_output=True, text=True, check=True)
            
            st.success("✅ Analysis Complete!")
            
            # --- MAIN DISPLAY ---
            col1, col2 = st.columns(2)
            
            with col1:
                st.subheader("Performance & Fairness Metrics")
                if os.path.exists("metrics_tradeoff.png"):
                    st.image("metrics_tradeoff.png", caption="Accuracy vs. Fairness across Mitigations")
                else:
                    st.error("Metrics graphic not generated.")
            
            with col2:
                st.subheader("Structural Bias Network")
                if os.path.exists("structural_bias.png"):
                    st.image("structural_bias.png", caption="Similarity Network generated by C++ Backend")
                else:
                    st.error("Graph visualization not generated.")
            
            with st.expander("Show Console Output"):
                st.code(result.stdout)
                
        except subprocess.CalledProcessError as e:
            st.error("⚠ Pipeline Execution Failed!")
            st.code(e.stderr)
            st.code(e.stdout)
